spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=discovery-service
info.app.version=0.0.1-SNAPSHOT
info.app.description=Eureka Discovery Server
